spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiry: ${JWT_ACCESS_EXPIRY:900}
    refresh-token-expiry: ${JWT_REFRESH_EXPIRY:604800}

logging:
  level:
    root: WARN
    com.r2s.uam: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
